version: '3.1'

services:

  mongo:
    image: mongo:latest
    volumes:
      - ./db:/data/db
    restart: always
    ports:
      - 27017:27017
    container_name: mongo_kpr_3

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    container_name: admin_kpr_3
  
  rest:
    build: express
    depends_on:
      - mongo
    environment:
      - DBURL=mongo
    ports:
      - 1499:1499
    container_name: rest_kpr_3
  
  gui:
    build:
      context: vuejs
      args:
        REST_HOST: 127.0.0.1
        REST_PORT: 1499
    depends_on:
      - rest
    ports:
      - 80:80
    container_name: gui_kpr_3