version: "3.1"

services:
  mongo:
    image: mongo:latest
    volumes:
      - ./db:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_AUTHENTICATION_MECHANISM: "SCRAM-SHA-1"
    command: ["mongod", "--auth", "--bind_ip_all"]
    container_name: mongo_db_backend_survey_app

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo_db_backend_survey_app
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    container_name: admin_panel_survey_app

  rest:
    build:
      context: express
      args:
        NODE_VERSION: 16.0
    depends_on:
      - mongo
    environment:
      - DBURL=mongo_db_backend_survey_app
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
    ports:
      - 1499:1499
    volumes:
      - ./db:/app/db
    container_name: rest_service_survey_app

  gui:
    build:
      context: vuejs
      args:
        REST_HOST: 127.0.0.1
        REST_PORT: 1499
    depends_on:
      - rest
    ports:
      - 80:80
    container_name: vue_gui_survey_app
