version: "3.1"

services:
  mongo:
    image: mongo:latest
    volumes:
      - ./db:/data/db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_AUTHENTICATION_MECHANISM: "SCRAM-SHA-1"
      MONGO_INITDB_SKIP: "true"
    command: ["mongod", "--auth", "--bind_ip_all"]
    container_name: mongo_db_backend_calls

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo_db_backend_calls
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    container_name: admin_panel_calls
